---
- name: Docker | Configure Proxy - Ubuntu systemd
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
  blockinfile:
    path: /lib/systemd/system/docker.service
    insertafter: '^\[Service\]$'
    content: |
      Environment="HTTP_PROXY={{ docker_http_proxy }}"
      Environment="HTTPS_PROXY={{ docker_http_proxy }}"
      Environment="NO_PROXY={{ docker_no_proxy }}"
